import Foundation
import JSONCodable
import RevenexxEnums

/// 
open class Form<T : Codable>: Codable {

    enum CodingKeys: String, CodingKey {
        case created_at = "created_at"
        case definition = "definition"
        case id = "id"
        case metadata = "metadata"
        case name = "name"
        case settings = "settings"
        case slug = "slug"
        case status = "status"
        case tenant_id = "tenant_id"
        case updated_at = "updated_at"
    }

    /// When the form was first stored.
    public let created_at: String?
    /// The form itself: a FormKit schema, held as a flat ARRAY of nodes (it defaults to `[]`, never to an object) and rendered verbatim by the storefront.
    /// 
    /// Read it as the field list. Every node carrying a non-empty `name` collects one value and writes it into a submission's `data` under exactly that name — the example below produces `{"company": …, "email": …, "message": …}` — while `$el` content nodes and `$rxStep` step markers collect nothing. Order is render order, and a `$rxStep` marker starts a new wizard step.
    /// 
    /// See the `FormKitNode` schema for what a node may carry.
    public let definition: [FormKitNode<T>]?
    /// The form's own id, generated by the database. It is what a submission's `form_id` points at and what the Cockpit and the storefront BFF hold once they have resolved a form, so it outlives a rename of the slug.
    public let id: String?
    /// Free-form metadata on the FORM, which this app neither reads nor writes: yours to key however an integration needs, stored and returned verbatim. (The metadata this app does write is on a SUBMISSION — see `FormSubmissionMetadata`.)
    public let metadata: [String: AnyCodable]?
    /// What this form is called in the Cockpit's form list. Operator-facing only — the storefront never renders it, so renaming a form breaks no page.
    public let name: String?
    /// Everything about a form that is not a field: what the storefront renders around the inputs, what happens after a successful submit, and who is told about it. Open jsonb, so an unknown key is stored and handed back rather than refused — the keys below are the ones something actually READS, and each says which reader that is. Null on a form nobody has configured, which is not an error: every one of these has a fallback.
    public let settings: FormSettings<T>?
    /// URL-safe identifier, unique per tenant. This is the name a storefront resolves a form by (`GET /v1/forms?slug=contact&status=live&limit=1`), so it is part of the page's contract: changing it changes which form a page renders. Lower-case letters, digits and inner hyphens.
    public let slug: String?
    /// Lifecycle. `draft` while it is being built; `live` once the storefront may render it — the cover BFF resolves live forms only, so a draft is a 404 on the storefront and never a broken page; `archived` for a form that is kept for its submissions but no longer offered. Default 'draft'.
    public let status: RevenexxEnums.FormStatus?
    /// The tenant this row belongs to — the store slug, not an id. Set by the platform from the authenticated context, never by a caller; a write that carries it is ignored, and no request can read another tenant's rows by sending a different one.
    public let tenant_id: String?
    /// When the form was last written. This app stamps it on every PUT, so it is the timestamp an editor sorts by.
    public let updated_at: String?

    init(
        created_at: String?,
        definition: [FormKitNode<T>]?,
        id: String?,
        metadata: [String: AnyCodable]?,
        name: String?,
        settings: FormSettings<T>?,
        slug: String?,
        status: RevenexxEnums.FormStatus?,
        tenant_id: String?,
        updated_at: String?
    ) {
        self.created_at = created_at
        self.definition = definition
        self.id = id
        self.metadata = metadata
        self.name = name
        self.settings = settings
        self.slug = slug
        self.status = status
        self.tenant_id = tenant_id
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.definition = try container.decodeIfPresent([FormKitNode<T>].self, forKey: .definition)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.settings = try container.decodeIfPresent(FormSettings<T>.self, forKey: .settings)
        self.slug = try container.decodeIfPresent(String.self, forKey: .slug)
        if let statusString = try container.decodeIfPresent(String.self, forKey: .status) {
            self.status = RevenexxEnums.FormStatus(rawValue: statusString)
        } else {
            self.status = nil
        }
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(definition, forKey: .definition)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(settings, forKey: .settings)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(status?.rawValue, forKey: .status)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "created_at": created_at as Any,
            "definition": definition?.map { $0.toMap() } as Any,
            "id": id as Any,
            "metadata": metadata as Any,
            "name": name as Any,
            "settings": settings?.toMap() as Any,
            "slug": slug as Any,
            "status": status?.rawValue as Any,
            "tenant_id": tenant_id as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> Form {
        return Form(
            created_at: map["created_at"] as? String,
            definition: (map["definition"] as? [[String: Any]] ?? []).map { FormKitNode.from(map: $0) },
            id: map["id"] as? String,
            metadata: map["metadata"] as? [String: AnyCodable],
            name: map["name"] as? String,
            settings: FormSettings.from(map: map["settings"] as! [String: Any]),
            slug: map["slug"] as? String,
            status: map["status"] as? String != nil ? FormStatus(rawValue: map["status"] as! String) : nil,
            tenant_id: map["tenant_id"] as? String,
            updated_at: map["updated_at"] as? String
        )
    }
}
