import Foundation
import JSONCodable
import RevenexxEnums

/// 
open class OrderListKindRow: Codable {

    enum CodingKeys: String, CodingKey {
        case code = "code"
        case created_at = "created_at"
        case description = "description"
        case descriptions = "descriptions"
        case id = "id"
        case is_default = "is_default"
        case is_system = "is_system"
        case labels = "labels"
        case position = "position"
        case tenant_id = "tenant_id"
        case title = "title"
        case tone = "tone"
        case updated_at = "updated_at"
    }

    /// What `lists.kind` stores. Lowercase, immutable once created — renaming it would orphan every list that carries it, so a merchant who wants a different code creates a new kind and moves the lists over.
    public let code: String?
    /// When the kind was created — the install for a seeded one.
    public let created_at: String?
    /// What this kind is FOR, in the tenant's own words — the sentence a select shows underneath the title. `descriptions` carries the localized forms. Same caveat as `title`: a kind seeded before 0.15.0 may hold a serialized locale map here (PE-450).
    public let description: String?
    /// Localized descriptions, keyed by language tag. Same fallback as `labels`: `description` is what a reader gets when their tag is missing.
    public let descriptions: [String: AnyCodable]?
    /// The kind, by id. Generated by the database and what every /orderlists/kinds/{id} route addresses — the `code` is the identity a LIST carries, the id is the identity a route takes.
    public let id: String?
    /// The kind a list created without one gets. Exactly one row carries it — promoting a kind demotes the previous holder — and the market-scoped `default_kind` setting still wins where a tenant set it.
    public let is_default: Bool?
    /// Seeded on install rather than created by the merchant. It changes nothing about what may be done to the row: a system kind is still renameable, still retirable, and still deletable once no list carries it.
    public let is_system: Bool?
    /// Localized titles, keyed by language tag. `title` is what a reader gets when their tag is missing, so this only ever adds languages — it never replaces the plain one.
    public let labels: [String: AnyCodable]?
    /// Where this kind sits in a select, ascending. Ties fall back to the code, so the order is stable.
    public let position: Int?
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    public let tenant_id: String?
    /// What a person reads, in the tenant's own words. `labels` carries the localized forms. Kinds seeded before 0.15.0 hold a serialized locale map here instead — the seed wrote its `{en, de}` map into this `text` column and left `labels` null, and Postgres stores such a map as its JSON text rather than refusing it (PE-450). Those rows are not repaired by the fix; a repair is a data change.
    public let title: String?
    /// Semantic badge colour. The client owns what each tone looks like; the kind only says what the value MEANS.
    public let tone: RevenexxEnums.OrderListKindRowTone?
    /// When the kind was last written.
    public let updated_at: String?

    init(
        code: String?,
        created_at: String?,
        description: String?,
        descriptions: [String: AnyCodable]?,
        id: String?,
        is_default: Bool?,
        is_system: Bool?,
        labels: [String: AnyCodable]?,
        position: Int?,
        tenant_id: String?,
        title: String?,
        tone: RevenexxEnums.OrderListKindRowTone?,
        updated_at: String?
    ) {
        self.code = code
        self.created_at = created_at
        self.description = description
        self.descriptions = descriptions
        self.id = id
        self.is_default = is_default
        self.is_system = is_system
        self.labels = labels
        self.position = position
        self.tenant_id = tenant_id
        self.title = title
        self.tone = tone
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.code = try container.decodeIfPresent(String.self, forKey: .code)
        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.descriptions = try container.decodeIfPresent([String: AnyCodable].self, forKey: .descriptions)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.is_default = try container.decodeIfPresent(Bool.self, forKey: .is_default)
        self.is_system = try container.decodeIfPresent(Bool.self, forKey: .is_system)
        self.labels = try container.decodeIfPresent([String: AnyCodable].self, forKey: .labels)
        self.position = try container.decodeIfPresent(Int.self, forKey: .position)
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        self.title = try container.decodeIfPresent(String.self, forKey: .title)
        if let toneString = try container.decodeIfPresent(String.self, forKey: .tone) {
            self.tone = RevenexxEnums.OrderListKindRowTone(rawValue: toneString)
        } else {
            self.tone = nil
        }
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(is_default, forKey: .is_default)
        try container.encodeIfPresent(is_system, forKey: .is_system)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(tone?.rawValue, forKey: .tone)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "code": code as Any,
            "created_at": created_at as Any,
            "description": description as Any,
            "descriptions": descriptions as Any,
            "id": id as Any,
            "is_default": is_default as Any,
            "is_system": is_system as Any,
            "labels": labels as Any,
            "position": position as Any,
            "tenant_id": tenant_id as Any,
            "title": title as Any,
            "tone": tone?.rawValue as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> OrderListKindRow {
        return OrderListKindRow(
            code: map["code"] as? String,
            created_at: map["created_at"] as? String,
            description: map["description"] as? String,
            descriptions: map["descriptions"] as? [String: AnyCodable],
            id: map["id"] as? String,
            is_default: map["is_default"] as? Bool,
            is_system: map["is_system"] as? Bool,
            labels: map["labels"] as? [String: AnyCodable],
            position: map["position"] as? Int,
            tenant_id: map["tenant_id"] as? String,
            title: map["title"] as? String,
            tone: map["tone"] as? String != nil ? OrderListKindRowTone(rawValue: map["tone"] as! String) : nil,
            updated_at: map["updated_at"] as? String
        )
    }
}
