import Foundation
import JSONCodable

/// 
open class OrderListSummary: Codable {

    enum CodingKeys: String, CodingKey {
        case created_at = "created_at"
        case id = "id"
        case item_count = "item_count"
        case kind = "kind"
        case metadata = "metadata"
        case name = "name"
        case organization_id = "organization_id"
        case owner_id = "owner_id"
        case owner_name = "owner_name"
        case `public` = "public"
        case shared = "shared"
        case tenant_id = "tenant_id"
        case updated_at = "updated_at"
    }

    /// When the list was created.
    public let created_at: String?
    /// The list, by id. Generated by the database and the only way to address it — every /orderlists/{id} route takes this uuid.
    public let id: String?
    /// Positions this list holds. Counted server-side so a badge costs no extra call — the collection deliberately does NOT carry the positions themselves.
    public let item_count: Int?
    /// What the list is FOR — the `code` of one of the tenant's own kinds (GET /orderlists/kinds). Nothing in this app branches on it: it groups and filters lists, it does not change how positions are stored or how a conversion runs. A merchant may add their own (reagent lists, sample lists) without a release of this app.
    public let kind: String?
    /// Free-form data the tenant keeps on the list — an ERP requisition number, a department, whatever an integration needs to recognise the list again. Never read by this app, and never merged: a write replaces the whole document.
    public let metadata: [String: AnyCodable]?
    /// What the buyer calls this list. Free text, at least one character, and not unique: two contacts may both keep a "Weekly office supplies". It is also the name a NEW cart gets when POST /orderlists/{id}/cart creates one.
    public let name: String?
    /// The organization the sharing is scoped to. Null means the list can only ever be the owner's own: `shared` is meaningless without it, because there is no set of people to share with. It is also what the order conversion hands the orders app as the buying organization.
    public let organization_id: String?
    /// The contact who owns the list. Ownership IS the authorization here: a caller the gateway resolved to a contact sees their own lists plus their organization's shared ones, and may write only their own — unless `shared_lists_editable` opens a shared list to the whole owning organization. Set once at create; no route moves a list to another owner.
    public let owner_id: String?
    /// The owner's display name as it stood when the list was created — a snapshot, so renaming the contact does not rewrite it. Carried so a shared list can say whose it is without a call to the contacts app.
    public let owner_name: String?
    /// Dead column: what `shared` was called before the 2026-06-20 rename (`public` is a reserved word in most SDK target languages). Nothing reads or writes it, so it is `false` on every list written since; it is still returned only because the additive provisioner never dropped the column. Read `shared` — this field says nothing about who may see the list.
    public let `public`: Bool?
    /// Whether the OWNING ORGANIZATION may see this list. False — the default — keeps it private to `owner_id`, and a foreign private list answers 404 rather than 403, so an outsider learns nothing from the difference. True lets every contact of `organization_id` READ it, and write it only where the tenant turned on the `shared_lists_editable` setting. A list with no `organization_id` shares with nobody however this is set.
    public let shared: Bool?
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    public let tenant_id: String?
    /// When the list or ANY of its positions last changed — adding, updating or removing a position touches the list — so this is the timestamp a "recently used" sort should read. It is also the default sort of GET /orderlists (`updated_at.desc`).
    public let updated_at: String?

    init(
        created_at: String?,
        id: String?,
        item_count: Int?,
        kind: String?,
        metadata: [String: AnyCodable]?,
        name: String?,
        organization_id: String?,
        owner_id: String?,
        owner_name: String?,
        `public`: Bool?,
        shared: Bool?,
        tenant_id: String?,
        updated_at: String?
    ) {
        self.created_at = created_at
        self.id = id
        self.item_count = item_count
        self.kind = kind
        self.metadata = metadata
        self.name = name
        self.organization_id = organization_id
        self.owner_id = owner_id
        self.owner_name = owner_name
        self.`public` = `public`
        self.shared = shared
        self.tenant_id = tenant_id
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.item_count = try container.decodeIfPresent(Int.self, forKey: .item_count)
        self.kind = try container.decodeIfPresent(String.self, forKey: .kind)
        self.metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.organization_id = try container.decodeIfPresent(String.self, forKey: .organization_id)
        self.owner_id = try container.decodeIfPresent(String.self, forKey: .owner_id)
        self.owner_name = try container.decodeIfPresent(String.self, forKey: .owner_name)
        self.`public` = try container.decodeIfPresent(Bool.self, forKey: .`public`)
        self.shared = try container.decodeIfPresent(Bool.self, forKey: .shared)
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(item_count, forKey: .item_count)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(organization_id, forKey: .organization_id)
        try container.encodeIfPresent(owner_id, forKey: .owner_id)
        try container.encodeIfPresent(owner_name, forKey: .owner_name)
        try container.encodeIfPresent(`public`, forKey: .`public`)
        try container.encodeIfPresent(shared, forKey: .shared)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "created_at": created_at as Any,
            "id": id as Any,
            "item_count": item_count as Any,
            "kind": kind as Any,
            "metadata": metadata as Any,
            "name": name as Any,
            "organization_id": organization_id as Any,
            "owner_id": owner_id as Any,
            "owner_name": owner_name as Any,
            "public": `public` as Any,
            "shared": shared as Any,
            "tenant_id": tenant_id as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> OrderListSummary {
        return OrderListSummary(
            created_at: map["created_at"] as? String,
            id: map["id"] as? String,
            item_count: map["item_count"] as? Int,
            kind: map["kind"] as? String,
            metadata: map["metadata"] as? [String: AnyCodable],
            name: map["name"] as? String,
            organization_id: map["organization_id"] as? String,
            owner_id: map["owner_id"] as? String,
            owner_name: map["owner_name"] as? String,
            public: map["public"] as? Bool,
            shared: map["shared"] as? Bool,
            tenant_id: map["tenant_id"] as? String,
            updated_at: map["updated_at"] as? String
        )
    }
}
