import Foundation
import JSONCodable

/// 
open class ProductCategories: Codable {

    enum CodingKeys: String, CodingKey {
        case category_id = "category_id"
        case created_at = "created_at"
        case id = "id"
        case position = "position"
        case product_id = "product_id"
        case source = "source"
    }

    /// The category it is filed into. One row per (product, category), whichever way it got there.
    public let category_id: String?
    /// When the row was created. Server-set — it is not part of any request body.
    public let created_at: String?
    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    public let id: String?
    /// Sort order of this product inside the category.
    public let position: Int?
    /// The product filed into the category. Deleting the product deletes the membership with it.
    public let product_id: String?
    /// How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
    public let source: String?

    init(
        category_id: String?,
        created_at: String?,
        id: String?,
        position: Int?,
        product_id: String?,
        source: String?
    ) {
        self.category_id = category_id
        self.created_at = created_at
        self.id = id
        self.position = position
        self.product_id = product_id
        self.source = source
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.category_id = try container.decodeIfPresent(String.self, forKey: .category_id)
        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.position = try container.decodeIfPresent(Int.self, forKey: .position)
        self.product_id = try container.decodeIfPresent(String.self, forKey: .product_id)
        self.source = try container.decodeIfPresent(String.self, forKey: .source)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(category_id, forKey: .category_id)
        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(product_id, forKey: .product_id)
        try container.encodeIfPresent(source, forKey: .source)
    }

    public func toMap() -> [String: Any] {
        return [
            "category_id": category_id as Any,
            "created_at": created_at as Any,
            "id": id as Any,
            "position": position as Any,
            "product_id": product_id as Any,
            "source": source as Any
        ]
    }

    public static func from(map: [String: Any] ) -> ProductCategories {
        return ProductCategories(
            category_id: map["category_id"] as? String,
            created_at: map["created_at"] as? String,
            id: map["id"] as? String,
            position: map["position"] as? Int,
            product_id: map["product_id"] as? String,
            source: map["source"] as? String
        )
    }
}
