import Foundation
import JSONCodable

/// 
open class ReferenceEntities: Codable {

    enum CodingKeys: String, CodingKey {
        case code = "code"
        case created_at = "created_at"
        case id = "id"
        case image = "image"
        case labels = "labels"
        case updated_at = "updated_at"
    }

    /// The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
    public let code: String?
    /// When the row was created. Server-set — it is not part of any request body.
    public let created_at: String?
    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    public let id: String?
    /// A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.
    public let image: String?
    /// What the entity is called, per language tag — the heading over its record list.
    public let labels: [String: AnyCodable]?
    /// When the row was last written. Server-set — it is not part of any request body.
    public let updated_at: String?

    init(
        code: String?,
        created_at: String?,
        id: String?,
        image: String?,
        labels: [String: AnyCodable]?,
        updated_at: String?
    ) {
        self.code = code
        self.created_at = created_at
        self.id = id
        self.image = image
        self.labels = labels
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.code = try container.decodeIfPresent(String.self, forKey: .code)
        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.image = try container.decodeIfPresent(String.self, forKey: .image)
        self.labels = try container.decodeIfPresent([String: AnyCodable].self, forKey: .labels)
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "code": code as Any,
            "created_at": created_at as Any,
            "id": id as Any,
            "image": image as Any,
            "labels": labels as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> ReferenceEntities {
        return ReferenceEntities(
            code: map["code"] as? String,
            created_at: map["created_at"] as? String,
            id: map["id"] as? String,
            image: map["image"] as? String,
            labels: map["labels"] as? [String: AnyCodable],
            updated_at: map["updated_at"] as? String
        )
    }
}
