import Foundation
import JSONCodable
import RevenexxEnums

/// 
open class Reservation: Codable {

    enum CodingKeys: String, CodingKey {
        case created_at = "created_at"
        case expires_at = "expires_at"
        case id = "id"
        case location_id = "location_id"
        case metadata = "metadata"
        case order_ref = "order_ref"
        case product_id = "product_id"
        case quantity = "quantity"
        case sku = "sku"
        case status = "status"
        case tenant_id = "tenant_id"
        case updated_at = "updated_at"
    }

    /// When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
    public let created_at: String?
    /// When this hold lapses. The sweeper — POST /inventories/reservations/sweep, and the 'expire-reservations' schedule that runs it every 15 minutes — releases everything past this moment exactly as a cancellation would, so an abandoned checkout stops holding stock on its own. Null means the row named no deadline: it is swept on its AGE instead once `reservation_ttl_minutes` is above 0, which is what makes turning that setting on retroactive.
    public let expires_at: String?
    /// The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    public let id: String?
    /// Which location is holding the goods for this order. Chosen at reserve time by the tenant's `allocation_strategy` — not by the caller, unless `ship_to.location_code` names one and the strategy is 'nearest'.
    public let location_id: String?
    /// Free-form, and one key this app writes itself: `backordered` — how much of this hold was not covered by stock on hand when it was taken. Absent on a hold that was fully covered.
    public let metadata: [String: AnyCodable]?
    /// The order this hold belongs to. The caller supplies it — this app mints nothing — and it is the handle POST /inventories/release and POST /inventories/commit act on, so it has to be the same string the order carries elsewhere. At least one character (CHECK `length(order_ref) > 0`). Not unique: an order holds one reservation per item, and they are released or committed together.
    public let order_ref: String?
    /// The product being held, copied from the reserve call. Null when the item was identified by SKU.
    public let product_id: String?
    /// How much is being held, ALWAYS POSITIVE — the database CHECK is `quantity > 0`, because a hold of nothing is not a hold. It is added to `stock_levels.reserved` while the status is `active` and taken off again when the hold is released, expires or is committed. The matching ledger booking carries the same number NEGATIVE (see `stock_movements.quantity`).
    public let quantity: Double?
    /// The article number being held, copied from the reserve call. Null when the item was identified by product id.
    public let sku: String?
    /// Where the hold stands in the reserve → commit | release lifecycle. 'active' — holding stock, and the ONLY status counted in `stock_levels.reserved`. 'committed' — the order shipped, so `on_hand` and `reserved` both fell. 'released' — the hold was given back, by POST /inventories/release or by the expiry sweeper. Both end states are final: nothing in this app moves a reservation back to active.
    public let status: RevenexxEnums.ReservationStatus?
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    public let tenant_id: String?
    /// When the hold last changed — in practice, when it moved out of `active`.
    public let updated_at: String?

    init(
        created_at: String?,
        expires_at: String?,
        id: String?,
        location_id: String?,
        metadata: [String: AnyCodable]?,
        order_ref: String?,
        product_id: String?,
        quantity: Double?,
        sku: String?,
        status: RevenexxEnums.ReservationStatus?,
        tenant_id: String?,
        updated_at: String?
    ) {
        self.created_at = created_at
        self.expires_at = expires_at
        self.id = id
        self.location_id = location_id
        self.metadata = metadata
        self.order_ref = order_ref
        self.product_id = product_id
        self.quantity = quantity
        self.sku = sku
        self.status = status
        self.tenant_id = tenant_id
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.expires_at = try container.decodeIfPresent(String.self, forKey: .expires_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.location_id = try container.decodeIfPresent(String.self, forKey: .location_id)
        self.metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        self.order_ref = try container.decodeIfPresent(String.self, forKey: .order_ref)
        self.product_id = try container.decodeIfPresent(String.self, forKey: .product_id)
        self.quantity = try container.decodeIfPresent(Double.self, forKey: .quantity)
        self.sku = try container.decodeIfPresent(String.self, forKey: .sku)
        if let statusString = try container.decodeIfPresent(String.self, forKey: .status) {
            self.status = RevenexxEnums.ReservationStatus(rawValue: statusString)
        } else {
            self.status = nil
        }
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(expires_at, forKey: .expires_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(location_id, forKey: .location_id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(order_ref, forKey: .order_ref)
        try container.encodeIfPresent(product_id, forKey: .product_id)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(status?.rawValue, forKey: .status)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "created_at": created_at as Any,
            "expires_at": expires_at as Any,
            "id": id as Any,
            "location_id": location_id as Any,
            "metadata": metadata as Any,
            "order_ref": order_ref as Any,
            "product_id": product_id as Any,
            "quantity": quantity as Any,
            "sku": sku as Any,
            "status": status?.rawValue as Any,
            "tenant_id": tenant_id as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> Reservation {
        return Reservation(
            created_at: map["created_at"] as? String,
            expires_at: map["expires_at"] as? String,
            id: map["id"] as? String,
            location_id: map["location_id"] as? String,
            metadata: map["metadata"] as? [String: AnyCodable],
            order_ref: map["order_ref"] as? String,
            product_id: map["product_id"] as? String,
            quantity: map["quantity"] as? Double,
            sku: map["sku"] as? String,
            status: map["status"] as? String != nil ? ReservationStatus(rawValue: map["status"] as! String) : nil,
            tenant_id: map["tenant_id"] as? String,
            updated_at: map["updated_at"] as? String
        )
    }
}
