import Foundation
import JSONCodable

/// 
open class StockLevel: Codable {

    enum CodingKeys: String, CodingKey {
        case created_at = "created_at"
        case id = "id"
        case location_id = "location_id"
        case metadata = "metadata"
        case on_hand = "on_hand"
        case product_id = "product_id"
        case reorder_point = "reorder_point"
        case reserved = "reserved"
        case sku = "sku"
        case tenant_id = "tenant_id"
        case updated_at = "updated_at"
    }

    /// When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
    public let created_at: String?
    /// The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    public let id: String?
    /// The location this balance is held at — a `locations` row of this tenant (GET /inventories/locations). There is ONE stock row per (location, item): the same SKU in three warehouses is three rows, and what a storefront shows is their sum (POST /inventories/availability). Deleting the location deletes its stock rows with it.
    public let location_id: String?
    /// Free-form data the tenant keeps on this stock row, and ONE key this app reads: `backorder`. A literal boolean `true` there opts this item into backorders while `backorder_policy` is 'allow_per_sku' — anything else, including the string "true", does not, and the reservation is refused with 422. That is how a merchant backorders the supplier-stocked half of a catalogue without promising the rest.
    public let metadata: [String: AnyCodable]?
    /// How much is PHYSICALLY at this location, INCLUDING the units already promised to orders. It is a BALANCE, not a movement: the running total of every `stock_movements` booking for this (location, item), and no request writes it directly — POST /inventories/receive raises it, POST /inventories/commit lowers it when the order ships, the adjust routes correct it, and a create/update body naming it has it DROPPED (422 if it names nothing else). Never negative: the database CHECK is `on_hand >= 0`, so a correction that would go below zero is refused with 422 and no setting overrides it — `allow_negative_stock` is about available stock, not about this. available (`on_hand` − `reserved`) is DERIVED and never stored — POST /inventories/availability and GET /inventories/reorder-alerts compute it on read.
    public let on_hand: Double?
    /// The product this row tracks, as the products app knows it. A row tracks a `product_id` or a `sku` — the database insists on at least one (CHECK `product_id is not null or sku is not null`) — and matching is exact: a row keyed by SKU is not found by product id.
    public let product_id: String?
    /// The available quantity at or below which this row belongs on the replenishment worklist (GET /inventories/reorder-alerts). Null falls back to the `reorder_point_default` setting, so replenishment works without a threshold per SKU; 0 never alerts, which is how one row opts out.
    public let reorder_point: Double?
    /// How much of `on_hand` is already promised — the sum of the ACTIVE reservations at this row. Reserving raises it; releasing, expiring or committing lowers it. Never negative (CHECK `reserved >= 0`). It does NOT reduce `on_hand`: the goods are still in the building until the shipment is committed, which is why the sellable figure is the difference of the two and not either one alone. available (`on_hand` − `reserved`) is DERIVED and never stored — POST /inventories/availability and GET /inventories/reorder-alerts compute it on read.
    public let reserved: Double?
    /// The article number this row tracks when there is no product id, which is the normal case for an ERP-stocked catalogue. Exact match, and the identity every stock call may use instead of a uuid.
    public let sku: String?
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    public let tenant_id: String?
    /// When this row was last written. Every balance change stamps it, so it doubles as "when did this item last move at this location".
    public let updated_at: String?

    init(
        created_at: String?,
        id: String?,
        location_id: String?,
        metadata: [String: AnyCodable]?,
        on_hand: Double?,
        product_id: String?,
        reorder_point: Double?,
        reserved: Double?,
        sku: String?,
        tenant_id: String?,
        updated_at: String?
    ) {
        self.created_at = created_at
        self.id = id
        self.location_id = location_id
        self.metadata = metadata
        self.on_hand = on_hand
        self.product_id = product_id
        self.reorder_point = reorder_point
        self.reserved = reserved
        self.sku = sku
        self.tenant_id = tenant_id
        self.updated_at = updated_at
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.location_id = try container.decodeIfPresent(String.self, forKey: .location_id)
        self.metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        self.on_hand = try container.decodeIfPresent(Double.self, forKey: .on_hand)
        self.product_id = try container.decodeIfPresent(String.self, forKey: .product_id)
        self.reorder_point = try container.decodeIfPresent(Double.self, forKey: .reorder_point)
        self.reserved = try container.decodeIfPresent(Double.self, forKey: .reserved)
        self.sku = try container.decodeIfPresent(String.self, forKey: .sku)
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        self.updated_at = try container.decodeIfPresent(String.self, forKey: .updated_at)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(location_id, forKey: .location_id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(on_hand, forKey: .on_hand)
        try container.encodeIfPresent(product_id, forKey: .product_id)
        try container.encodeIfPresent(reorder_point, forKey: .reorder_point)
        try container.encodeIfPresent(reserved, forKey: .reserved)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(updated_at, forKey: .updated_at)
    }

    public func toMap() -> [String: Any] {
        return [
            "created_at": created_at as Any,
            "id": id as Any,
            "location_id": location_id as Any,
            "metadata": metadata as Any,
            "on_hand": on_hand as Any,
            "product_id": product_id as Any,
            "reorder_point": reorder_point as Any,
            "reserved": reserved as Any,
            "sku": sku as Any,
            "tenant_id": tenant_id as Any,
            "updated_at": updated_at as Any
        ]
    }

    public static func from(map: [String: Any] ) -> StockLevel {
        return StockLevel(
            created_at: map["created_at"] as? String,
            id: map["id"] as? String,
            location_id: map["location_id"] as? String,
            metadata: map["metadata"] as? [String: AnyCodable],
            on_hand: map["on_hand"] as? Double,
            product_id: map["product_id"] as? String,
            reorder_point: map["reorder_point"] as? Double,
            reserved: map["reserved"] as? Double,
            sku: map["sku"] as? String,
            tenant_id: map["tenant_id"] as? String,
            updated_at: map["updated_at"] as? String
        )
    }
}
