import Foundation
import JSONCodable
import RevenexxEnums

/// 
open class StockMovement: Codable {

    enum CodingKeys: String, CodingKey {
        case created_at = "created_at"
        case id = "id"
        case location_id = "location_id"
        case metadata = "metadata"
        case order_ref = "order_ref"
        case product_id = "product_id"
        case quantity = "quantity"
        case reason = "reason"
        case sku = "sku"
        case tenant_id = "tenant_id"
        case type = "type"
    }

    /// When the booking was written — the ledger's own clock and its natural order, which is why `?order=created_at.desc` is the feed order. There is no `updated_at`: the ledger is append-only, and a correction is another booking rather than an edit.
    public let created_at: String?
    /// The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    public let id: String?
    /// Where the booking happened. Copied from the call that caused it, not a foreign key — a movement outlives the location row it names.
    public let location_id: String?
    /// Free-form, and two keys this app writes itself: `backordered` — on a `reserve` booking, how much of the hold was not covered by stock on hand; `shortfall` — on a `shipment` booking, how much was committed that was not physically there (`on_hand` floors at 0, so the difference is recorded here instead of vanishing). Neither key is present on a booking that needed neither.
    public let metadata: [String: AnyCodable]?
    /// The order this booking belongs to, for the bookings an order causes — 'reserve', 'release', 'shipment', and a 'restock' that names one. Null for a receipt or a stocktake. It is the join that reconstructs one order's whole stock history: GET /inventories/movements?order_ref=…
    public let order_ref: String?
    /// The product this booking is for, copied from the call. Null when the item was identified by SKU.
    public let product_id: String?
    /// The SIGNED size of the booking — a DELTA, never a balance, and deliberately the one quantity in this app with no bound on it. `stock_levels.on_hand`/`reserved` and `reservations.quantity` each carry a CHECK; this column carries none, because the SIGN is the direction of the booking and a rule that forbade one of them would forbid half the ledger. Positive adds to what the location holds ('inbound', 'restock', a positive 'adjustment'); negative takes it away ('shipment', a negative 'adjustment'). 'reserve' books the NEGATIVE of the quantity held (−5 for a hold of 5) while the reservation row itself carries +5: the movement says which way stock moved, the reservation says how much is being held. Summing this column for one (location, item) reconstructs `on_hand` — which is what makes the ledger an audit trail and not a log.
    public let quantity: Double?
    /// Why the booking happened, in a person's words — a delivery note number, 'stocktake 2026-03', 'damaged in transit'. Whether one is owed is the `movement_reason_required` setting ('none' | 'adjustments' | 'all'), never this column, which stays nullable so the tenant that requires nothing is not forced. The expiry sweeper writes 'reservation expired' on the releases it makes.
    public let reason: String?
    /// The article number this booking is for, copied from the call. Null when the item was identified by product id.
    public let sku: String?
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    public let tenant_id: String?
    /// What the booking records. 'inbound' — a receipt (+on_hand). 'adjustment' — a manual correction, the only type whose sign can go either way. 'reserve' — a hold taken for an order (`reserved` up, `on_hand` untouched). 'release' — a hold given back, by cancellation or by the expiry sweeper. 'shipment' — a committed reservation leaving the building (`on_hand` and `reserved` both down). 'restock' — a return that rejoined sellable stock. GET /inventories/vocabularies/movement-types serves these with the words a person reads for them.
    public let type: RevenexxEnums.StockMovementType?

    init(
        created_at: String?,
        id: String?,
        location_id: String?,
        metadata: [String: AnyCodable]?,
        order_ref: String?,
        product_id: String?,
        quantity: Double?,
        reason: String?,
        sku: String?,
        tenant_id: String?,
        type: RevenexxEnums.StockMovementType?
    ) {
        self.created_at = created_at
        self.id = id
        self.location_id = location_id
        self.metadata = metadata
        self.order_ref = order_ref
        self.product_id = product_id
        self.quantity = quantity
        self.reason = reason
        self.sku = sku
        self.tenant_id = tenant_id
        self.type = type
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.created_at = try container.decodeIfPresent(String.self, forKey: .created_at)
        self.id = try container.decodeIfPresent(String.self, forKey: .id)
        self.location_id = try container.decodeIfPresent(String.self, forKey: .location_id)
        self.metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        self.order_ref = try container.decodeIfPresent(String.self, forKey: .order_ref)
        self.product_id = try container.decodeIfPresent(String.self, forKey: .product_id)
        self.quantity = try container.decodeIfPresent(Double.self, forKey: .quantity)
        self.reason = try container.decodeIfPresent(String.self, forKey: .reason)
        self.sku = try container.decodeIfPresent(String.self, forKey: .sku)
        self.tenant_id = try container.decodeIfPresent(String.self, forKey: .tenant_id)
        if let typeString = try container.decodeIfPresent(String.self, forKey: .type) {
            self.type = RevenexxEnums.StockMovementType(rawValue: typeString)
        } else {
            self.type = nil
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(created_at, forKey: .created_at)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(location_id, forKey: .location_id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(order_ref, forKey: .order_ref)
        try container.encodeIfPresent(product_id, forKey: .product_id)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(tenant_id, forKey: .tenant_id)
        try container.encodeIfPresent(type?.rawValue, forKey: .type)
    }

    public func toMap() -> [String: Any] {
        return [
            "created_at": created_at as Any,
            "id": id as Any,
            "location_id": location_id as Any,
            "metadata": metadata as Any,
            "order_ref": order_ref as Any,
            "product_id": product_id as Any,
            "quantity": quantity as Any,
            "reason": reason as Any,
            "sku": sku as Any,
            "tenant_id": tenant_id as Any,
            "type": type?.rawValue as Any
        ]
    }

    public static func from(map: [String: Any] ) -> StockMovement {
        return StockMovement(
            created_at: map["created_at"] as? String,
            id: map["id"] as? String,
            location_id: map["location_id"] as? String,
            metadata: map["metadata"] as? [String: AnyCodable],
            order_ref: map["order_ref"] as? String,
            product_id: map["product_id"] as? String,
            quantity: map["quantity"] as? Double,
            reason: map["reason"] as? String,
            sku: map["sku"] as? String,
            tenant_id: map["tenant_id"] as? String,
            type: map["type"] as? String != nil ? StockMovementType(rawValue: map["type"] as! String) : nil
        )
    }
}
